import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Musicplayer from "./Components/Musicplayer";
import { PlayerProvider } from "./lib/PlayerContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mazid Music",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PlayerProvider>
          <main className="min-h-screen bg-[#0F0D20]">
            {children}
            <Musicplayer />
          </main>
        </PlayerProvider>
      </body>
    </html>
  );
}
